name: CI-CD-PipeLine-to-AWS-ElasticBeastalk
env:
  EB_PACKAGES_S3_BUCKET_NAME: "jeyhun-flask-application-packages"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "MyFlask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-north-1"
  
on:
  push: 
    branches: 
      - master 

jobs:
#CI Part
  my-ci-part: 
    runs-on: ubuntu-latest 

    steps:
    - name: Git clone our repo 
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*    

    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 bucker 
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGES_S3_BUCKET_NAME }}/
      
    - name : Print Happy Message for CI finish
      run  : echo " CI Pipeline part Finished successfully" 
### CD PART
  my-cd-part:
    runs-on: ubuntu-latest 
    needs: [my-ci-part] #After CI will success cd will start 

    steps:
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: Create new ElasticBeanStalk Application 
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_PACKAGES_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label="Version-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"
### Deploy 
    - name: Deploy new ElasticBeanstalk Application  Version 
      run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Version-${{ github.sha }}"

    - name : Print Happy Message for CI finish
      run  : echo " CI Pipeline part Finished successfully" 
